image: enra64/godot-android-ci:firsttry

stages:
  - export
  - deploy

variables:
  EXPORT_NAME: grab-cat

before_script:
  - mkdir -v -p build/linux
  - mkdir -v -p build/windows
  - mkdir -v -p build/mac
  - mkdir -v -p build/web
  - mkdir -v -p build/android

linux:
  stage: export
  script:
    - godot -v --export "Linux/X11" ./build/linux/$EXPORT_NAME.x86_64
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/linux

android_debug:
  stage: export
  before_script:
    # This is simply (semi-manual :-)) double-check if editor settings are OK for debug export
    - grep android ~/.config/godot/editor_settings-3.tres
    - ls -l /usr/lib/jvm/java-8-openjdk-amd64/bin/jarsigner
    - ls -l /sdk/debug.keystore
    - ls -l /sdk/platform-tools/adb
    # Create directory for artifacts
    - mkdir -v -p export/android
  script:
    - godot --quiet --export-debug "Android" export/android/${APP_NAME}-debug.apk >&-
    - ls export/android/${APP_NAME}-debug.apk # ls
  artifacts: 
    name: ${APP_NAME}-debug
    paths:
      - export/android/${APP_NAME}-debug.apk

windows:
  stage: export
  script:
    - godot -v --export "Windows Desktop" ./build/windows/$EXPORT_NAME.exe
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/windows

mac:
  stage: export
  script:
    - godot -v --export "Mac OSX" ./build/mac/$EXPORT_NAME.zip
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/mac

web:
  stage: export
  script:
    - godot -v --export "HTML5" ./build/web/index.html
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/web

# GitLab Pages Deploy
pages:
  stage: deploy
  only:
    refs:
      - master
  dependencies:
    - web
  script:
    # This ensures the `pages` branch is available.
    - git fetch
    - git checkout pages
    - rm -f *.md
    - mv build/web/** ./public
  artifacts:
    paths:
      - public

# Itch.io Deploy
itchio:linux:
  stage: deploy
  only:
    refs:
      - master
  script:
    - butler push ./build/linux $ITCHIO_USERNAME/$ITCHIO_GAME:linux
  dependencies:
    - linux

itchio:windows:
  stage: deploy
  only:
    refs:
      - master
  script:
    - butler push ./build/windows $ITCHIO_USERNAME/$ITCHIO_GAME:windows
  dependencies:
    - windows

itchio:macosx:
  stage: deploy
  only:
    refs:
      - master
  script:
    - butler push ./build/mac $ITCHIO_USERNAME/$ITCHIO_GAME:mac
  dependencies:
    - mac

